---
title: "assignment1"
format: html
editor: visual
---

```{r}
rm(list=ls())

# Laster inn pakker. 
suppressPackageStartupMessages({
library(tidyverse)
library(lubridate)
library(zoo)
})

# Laster inn data. 
suppressWarnings({
df_lowertropo <- read_table2("https://www.nsstc.uah.edu/data/msu/v6.0/tlt/uahncdc_lt_6.0.txt")
df_midtropo <- read_table2("http://vortex.nsstc.uah.edu/data/msu/v6.0/tmt/uahncdc_mt_6.0.txt")
df_tropo <- read_table2("http://vortex.nsstc.uah.edu/data/msu/v6.0/ttp/uahncdc_tp_6.0.txt")
df_lowerstrato <- read_table2("http://vortex.nsstc.uah.edu/data/msu/v6.0/tls/uahncdc_ls_6.0.txt")
})
```

```{r}
# Fjerner rader dynamisk. 
df_lowertropo <- df_lowertropo[1:which(df_lowertropo$Year %in% "Year")-1, ]
df_midtropo <- df_midtropo[1:which(df_midtropo$Year %in% "Year")-1, ]
df_tropo <- df_tropo[1:which(df_tropo$Year %in% "Year")-1, ]
df_lowerstrato <- df_lowerstrato[1:which(df_lowerstrato$Year %in% "Year")-1, ]
```

```{r}
suppressWarnings({
df_lowertropo <- df_lowertropo %>% # Lager en date kolonne. 
   mutate(Date = ymd(paste(df_lowertropo$Year, df_lowertropo$Mo, 1, sep="-"))) %>% 
  select(Date, Globe) %>% # Velger ut de variablene jeg har bruk for. 
  mutate(var = 'Lower Tropo') # Gir den enklere navn. 

df_midtropo <- df_midtropo %>%  # Lager en date kolonne
   mutate(Date = ymd(paste(df_midtropo$Year, df_midtropo$Mo, 1, sep="-"))) %>%
  select(Date, Globe) %>% # Velger ut de variablene jeg har bruk for.
  mutate(var = 'Mid Tropo') # Gir den enklere navn.

df_tropo <- df_tropo %>% # Lager en date kolonne.
   mutate(Date = ymd(paste(df_tropo$Year, df_tropo$Mo, 1, sep="-"))) %>%
  select(Date, Globe) %>% # Velger ut de variablene jeg har bruk for. 
  mutate(var = 'Tropopause') # Gir den enklere navn.

df_lowerstrato <- df_lowerstrato %>% # Lager en date kolonne. 
   mutate(Date = ymd(paste(df_lowerstrato$Year, df_lowerstrato$Mo, 1, sep="-"))) %>%
  select(Date, Globe) %>%  # Velger ut de variablene jeg har bruk for.
  mutate(var = 'Lower Strato') # Gir den enklere navn.
})
```

```{r}
# Regner ut rollmean for alle datasettene: 
df_lowertropo <- df_lowertropo %>% 
  mutate(Globe = as.numeric(Globe)) %>% 
  mutate(GlobeMovingMean = rollmean(Globe, k = 12, fill = NA, align = "right")) %>% 
  select(-Globe) # Fjerner  globe, trenger den ikke mer. 

df_midtropo <- df_midtropo %>%
  mutate(Globe = as.numeric(Globe)) %>% 
  mutate(GlobeMovingMean = rollmean(Globe, k = 12, fill = NA, align = "right")) %>% 
  select(-Globe) # Fjerner  globe, trenger den ikke mer. 

df_tropo <- df_tropo %>% 
  mutate(Globe = as.numeric(Globe)) %>%
  mutate(GlobeMovingMean = rollmean(Globe, k = 12, fill = NA, align = "right")) %>% 
  select(-Globe) # Fjerner  globe, trenger den ikke mer. 

df_lowerstrato <- df_lowerstrato %>% 
  mutate(Globe = as.numeric(Globe)) %>%
  mutate(GlobeMovingMean = rollmean(Globe, k = 12, fill = NA, align = "right")) %>% 
  select(-Globe) # Fjerner  globe, trenger den ikke mer. 
```

```{r}
# Binder datasettene sammen. 
df_temp <- rbind(df_lowerstrato, df_lowertropo, df_tropo, df_midtropo)

df_temp_mean <- df_temp %>% 
  group_by(Date) %>%
  summarize(Average = mean(GlobeMovingMean)) # Her renger jeg gjennomsnitt av rollmean. Kaller den nye variabelen for 'Average'.

df_temp_mean <- df_temp_mean %>% 
  select(-Date) # Fjerner date siden jeg skal binde datasettene og trenger  kun en kolonne med date. 
```

```{r}
df_tidy <- cbind(df_temp, df_temp_mean) # Binder datasettene.

df_tidy <- df_tidy %>% 
  pivot_wider(names_from = var, values_from = GlobeMovingMean) %>% 
  filter(Date >= '1980-01-01') # Gjør datasettet bredere, da det er mest ryddig. 

View(df_tidy) # Datasettet er nå ryddig, og kan plottes i figur. 
```

```{r}
names(df_tidy) # Har navnene tilgjengelig, enklere når de  skrives i ggplot. 
fig <- ggplot() + # Kaller plott fig
  geom_line(data = df_tidy,aes(x=Date,y=Average,col="Average")) +
  geom_line(data = df_tidy,aes(x=Date,y= `Lower Strato`,col="Lower Strato")) +
  geom_line(data = df_tidy,aes(x=Date,y= `Lower Tropo`,col="Lower Tropo")) +
  geom_line(data = df_tidy,aes(x=Date,y= `Tropopause`,col="Tropopause")) +
  geom_line(data = df_tidy,aes(x=Date,y= `Mid Tropo`,col="Mid Tropo")) + theme_bw() + ggtitle("Four Locations right alligned Moving Average." , subtitle = "- and their Average") + ylab('MovingAvg')

fig # Slik ble det. 
```
